version: '3.8'

services:
  # PostgreSQL Database for development
  db:
    image: postgres:15-alpine
    container_name: seminario_db_dev
    environment:
      POSTGRES_DB: seminario_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: psswd
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./Dump20180203.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    networks:
      - seminario-dev-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Adminer for database management
  adminer:
    image: adminer
    container_name: seminario_adminer
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - seminario-dev-network
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  postgres_dev_data:
    driver: local

networks:
  seminario-dev-network:
    driver: bridge 