[variables]
NODE_ENV = "production"
TURBO_TELEMETRY_DISABLED = "1"

[phases.setup]
nixPkgs = ["nodejs_18", "pnpm"]

[phases.install]
cmds = [
  "corepack enable",
  "pnpm install --frozen-lockfile --filter \"@seminario/api...\" --filter \"@seminario/portal...\" --filter \"@seminario/shared-auth...\" --filter \"@seminario/shared-config...\" --filter \"@seminario/shared-dtos...\" --filter '!@seminario/shared-tests'"
]

[phases.build]
cmds = [
  "pnpm turbo run build --concurrency=1 --no-daemon --filter \"@seminario/api...\" --filter \"@seminario/portal...\" --filter '!@seminario/shared-tests'"
]

[start]
cmd = "bash scripts/nixpacks-start.sh"
