# Nixpacks Configuration for Sistema Acadêmico
# https://nixpacks.com/docs/configuration/file

providers = ["node"]

[variables]
NODE_ENV = "production"
PORT = "4000"

[phases.setup]
nixPkgs = ["nodejs_18", "pnpm", "postgresql"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = [
    "pnpm run build",
    "chmod +x scripts/nixpacks-start.sh"
]

[start]
cmd = "./scripts/nixpacks-start.sh"

[staticAssets]
"/public" = "apps/portal/dist"
