# Nixpacks Configuration for Sistema Acadêmico
# https://nixpacks.com/docs/configuration/file

providers = ["node"]

[variables]
NODE_ENV = "production"
PORT = "4000"

[phases.setup]
nixPkgs = ["nodejs_18", "pnpm", "postgresql"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = [
    "echo '🔨 Building packages...'",
    "pnpm run build --filter=@seminario/shared-config",
    "pnpm run build --filter=@seminario/shared-auth", 
    "pnpm run build --filter=@seminario/shared-dtos",
    "pnpm run build --filter=@seminario/shared-tests",
    "echo '🔨 Building API...'",
    "cd apps/api && pnpm run build",
    "echo '🔨 Building Portal...'", 
    "cd apps/portal && pnpm run build",
    "echo '🔧 Setting permissions...'",
    "chmod +x scripts/nixpacks-start.sh",
    "ls -l scripts/nixpacks-start.sh",
    "echo '✅ Build completed!'"
]

# Start command using bash explicitly to avoid dependency on executable bit
# This prevents "Permission denied" errors if +x permissions are lost between build layers
[start]
cmd = "bash scripts/nixpacks-start.sh"

[staticAssets]
"/public" = "apps/portal/dist"
